services:
  # Yerel MongoDB'yi siliyoruz/devre dışı bırakıyoruz çünkü artık Atlas (Bulut) kullanıyoruz.
  # Eğer yerel DB konteynırı depends_on içinde kalırsa servisler Atlas'a bağlanmak yerine 
  # yerel DB'nin açılmasını bekleyip hata verebilir.

  api-gateway:
    build: ./api-gateway
    container_name: usta-api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - USER_SERVICE_URL=user-service:50052
      - PROVIDER_SERVICE_URL=provider-service:50051
      - ORDER_SERVICE_URL=order-service:50054
      - REVIEW_SERVICE_URL=review-service:50055
      - NOTIFICATION_SERVICE_URL=notification-service:50056
    depends_on:
      - user-service
      - provider-service

  user-service:
    build: ./user-service
    container_name: usta-user-service
    environment:
      - MONGO_URI=mongodb+srv://selmanyilmaz:morinyo1907@cs306cluster.h6hnm1n.mongodb.net/usta_db?retryWrites=true&w=majority
    ports:
      - "50052:50052"

  provider-service:
    build: ./provider-service
    container_name: usta-provider-service
    environment:
      - MONGO_URI=mongodb+srv://selmanyilmaz:morinyo1907@cs306cluster.h6hnm1n.mongodb.net/usta_db?retryWrites=true&w=majority
      - DATABASE_URL=mongodb+srv://selmanyilmaz:morinyo1907@cs306cluster.h6hnm1n.mongodb.net/usta_db?retryWrites=true&w=majority
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
    ports:
      - "50051:50051"

  order-service:
    build: ./order-service
    container_name: usta-order-service
    environment:
      - MONGO_URI=mongodb+srv://selmanyilmaz:morinyo1907@cs306cluster.h6hnm1n.mongodb.net/usta_db?retryWrites=true&w=majority
    ports:
      - "50054:50054"

  review-service:
    build: ./review-service
    container_name: usta-review-service
    environment:
      - MONGO_URI=mongodb+srv://selmanyilmaz:morinyo1907@cs306cluster.h6hnm1n.mongodb.net/usta_db?retryWrites=true&w=majority
    ports:
      - "50055:50055"

  notification-service:
    build: ./notification-service
    container_name: usta-notification-service
    environment:
      - MONGO_URI=mongodb+srv://selmanyilmaz:morinyo1907@cs306cluster.h6hnm1n.mongodb.net/usta_db?retryWrites=true&w=majority
    ports:
      - "50056:50056"

# Artık yerel volume ihtiyacımız kalmadı ama hata vermemesi için bırakabilirsin.
volumes:
  mongo_data: