services:
  mongodb:
    image: mongo:6.0
    container_name: usta_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api-gateway:
    build: ./api-gateway
    container_name: usta-api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - USER_SERVICE_URL=user-service:50052
      - PROVIDER_SERVICE_URL=provider-service:50051
      - ORDER_SERVICE_URL=order-service:50054
      - REVIEW_SERVICE_URL=review-service:50055
      - NOTIFICATION_SERVICE_URL=notification-service:50056
    depends_on:
      - user-service
      - provider-service

  user-service:
    build: ./user-service
    container_name: usta-user-service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/usta_db
    ports:
      - "50052:50052"
    depends_on:
      - mongodb

  provider-service:
    build: ./provider-service
    container_name: usta-provider-service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/usta_db
      - DATABASE_URL=mongodb://mongodb:27017/usta_db
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
    ports:
      - "50051:50051"
    depends_on:
      - mongodb

  order-service:
    build: ./order-service
    container_name: usta-order-service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/usta_db
    ports:
      - "50054:50054"
    depends_on:
      - mongodb

  review-service:
    build: ./review-service
    container_name: usta-review-service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/usta_db
    ports:
      - "50055:50055"
    depends_on:
      - mongodb

  notification-service:
    build: ./notification-service
    container_name: usta-notification-service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/usta_db
    ports:
      - "50056:50056"
    depends_on:
      - mongodb

volumes:
  mongo_data: